### ISSUE TITLE
Continuous modeling with 0.2.0 broken 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-modeler#21]
When using zeebe-modeler 0.2.0 the continuous modeling from a node is broken. See gif for example, this is are the stacktraces shown in the log:

```
Error: no shape type specified
    at ElementFactory.createBpmnElement (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:31261:13)
    at ElementFactory.create (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:31248:15)
    at Modeling._create (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:94749:33)
    at Modeling.createConnection (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:94507:21)
    at Modeling.connect (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:31531:15)
    at AppendShapeHandler.postExecute (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:94873:20)
    at CommandStack._internalExecute (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:85561:15)
    at CommandStack.execute (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:85298:8)
    at Modeling.appendShape (file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:94618:22)
    at file:///home/menski/.local/opt/zeebe-modeler/resources/app.asar/public/index.js:91600:24  [error]
```

![zeebe-modeler](https://user-images.githubusercontent.com/516296/48473784-7fb15080-e7f9-11e8-9717-e397b55dd557.gif)

**Comment by menski** [comment]
Hi @dominikhrn,

we experienced this on Linux and Windows, do you have an idea what is causing this behavior? It breaks the whole modeling afterwards.

**Comment by dominikhrn** [comment]
I guess the problem is in the CustomContextPadProvider.
I will check that later.

**Comment by menski** [comment]
Thanks @dominikhrn

**Comment by dominikhrn** [comment]
@menski 
The problem was in the CustomRules.
I had to disable them.
I guess that is no problem anymore because parallel flows are enabled in the current release right?
If not just open an issue with modeling rules that should be provided.

**Comment by menski** [comment]
Hi @dominikhrn,

Yes parallel flows are now supported. Thanks for your this fast fix, it seems to work now without problems. :balloon:
