### ISSUE TITLE
Npm error on execute all checks while building the app

### ISSUE THREAD

**Issue by vincentgiraud** [zeebe-io/zeebe-modeler#249]
__Describe the Bug__

Executing all checks (lint, test and build) during the build process ends up with errors

__Steps to Reproduce__

1. git checkout develop
2. npm install
3. npm run all

> zeebe-modeler-builder@0.5.0 all /Users/v/Dev/zeebe-modeler
> run-s clean lint test "build -- {@}" --

> zeebe-modeler-builder@0.5.0 clean /Users/v/Dev/zeebe-modeler
> del-cli 'dist/*' app/public

> zeebe-modeler-builder@0.5.0 lint /Users/v/Dev/zeebe-modeler
> eslint .

> zeebe-modeler-builder@0.5.0 test /Users/v/Dev/zeebe-modeler
> run-s *:test

> zeebe-modeler-builder@0.5.0 app:test /Users/v/Dev/zeebe-modeler
> nyc --reporter lcov --exclude "app/test/**" --exclude "app/**/__tests__" mocha --require ./app/test/expect "app/**/*-spec.js"

/Users/v/Dev/zeebe-modeler/app/lib/window-manager/__tests__/window-manager-spec.js:197
  isFullScreen = () => !!this._isFullScreen
               ^

SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module.replacementCompile (/Users/v/Dev/zeebe-modeler/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.<anonymous> (/Users/v/Dev/zeebe-modeler/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/v/Dev/zeebe-modeler/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/v/Dev/zeebe-modeler/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/v/Dev/zeebe-modeler/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/v/Dev/zeebe-modeler/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Module.replacementCompile (/Users/v/Dev/zeebe-modeler/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.<anonymous> (/Users/v/Dev/zeebe-modeler/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeebe-modeler-builder@0.5.0 app:test: `nyc --reporter lcov --exclude "app/test/**" --exclude "app/**/__tests__" mocha --require ./app/test/expect "app/**/*-spec.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeebe-modeler-builder@0.5.0 app:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/v/.npm/_logs/2020-09-03T10_28_43_253Z-debug.log
ERROR: "app:test" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeebe-modeler-builder@0.5.0 test: `run-s *:test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeebe-modeler-builder@0.5.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/v/.npm/_logs/2020-09-03T10_28_43_279Z-debug.log
ERROR: "test" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeebe-modeler-builder@0.5.0 all: `run-s clean lint test "build -- {@}" --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeebe-modeler-builder@0.5.0 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/v/.npm/_logs/2020-09-03T10_28_43_313Z-debug.log

__Expected Behavior__

SUCCESS

__Environment__

- OS: MacOS 10.15.3
- Zeebe Modeler Version: develop
- NodeJS: v11.0.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Seems like we introduced changes which require at least NodeJS@12: https://stackoverflow.com/a/47517218. Updating to the latest NodeJS version will do the trick. However, we will check whether can fix the problem for older node version.

**Comment by vincentgiraud** [comment]
Thanks @pinussilvestrus I upgraded node to v12.18.3 and got passed npm run all succesfully.

I hitting another down the road with 'npm run dev' but I'll open a separate ticket.
