### ISSUE TITLE
"npm install" went error on mac

### ISSUE THREAD

**Issue by xiuxiu** [zeebe-io/zeebe-modeler#287]
just cloned the repo and tried to run "npm install". The error message is like:

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../lib/cli.js'
Require stack:
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/npm/bin/npm-cli.js' ]
}

- OS: [e.g. MacOS 10.2, Windows 10]
- Zeebe Modeler Version: [e.g. 2.0.0]

**Comment by MaxTru** [comment]
This seems to be an issue with your node installation. 

Could you please verify your node installation? Maye running `npm i npm -g ` helps.

If that does not help, could you please check whether you can install some other npm project (so to verify that this is a zeebe-modeler repo specific issue)?

**Comment by nikku** [comment]
Closing this issue. 

If you provide further pointers into your setup, we may be able to help you.
